name: Build and Test DotNet Sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    # 检出代码
    - name: Checkout Code
      uses: actions/checkout@v4

    # 设置 .NET SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x  # 使用目标 .NET 版本

    # 恢复依赖
    - name: Restore Dependencies
      run: dotnet restore dotnet-sample/dotnet-sample.sln

    # 构建项目
    - name: Build Project
      run: dotnet build dotnet-sample/dotnet-sample.sln --configuration ${{ matrix.configuration }} --no-restore

    # 运行测试
    - name: Run Tests
      run: dotnet test dotnet-sample/dotnet-sample.sln --configuration ${{ matrix.configuration }} --no-build

    # 发布构建产物
    - name: Publish Artifacts
      run: dotnet publish dotnet-sample/dotnet-sample.sln --configuration ${{ matrix.configuration }} --output ./output
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1  # 禁用遥测

    # 上传构建产物
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build-Output-${{ matrix.configuration }}
        path: dotnet-sample/output
