name: Build and Test DotNet Sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    # 检出代码
    - name: Checkout Code
      uses: actions/checkout@v4

    # 设置 .NET SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x  # 使用目标 .NET 版本

    # 配置 JFrog CLI
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2
      with:
        version: 2.39.3  # 明确指定 JFrog CLI 的版本

    # 配置 Artifactory
    - name: Configure JFrog Artifactory
      run: |
        jfrog rt config --url=${{ secrets.JFROG_URL }} \
                        --user=${{ secrets.JFROG_USER }} \
                        --password=${{ secrets.JFROG_PASSWORD }}

    # 配置 NuGet 源
    - name: Configure JFrog NuGet
      run: |
        jfrog rt nuget-config --repo-resolve=nuget-repo \
                              --repo-deploy=nuget-repo \
                              --url=${{ secrets.JFROG_URL }} \
                              --user=${{ secrets.JFROG_USER }} \
                              --password=${{ secrets.JFROG_PASSWORD }}
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    # 使用 Artifactory 下载依赖
    - name: Restore Dependencies from Artifactory
      run: |
        jfrog rt dotnet restore dotnet-sample/dotnet-sample.sln \
          --build-name="DotNet-Sample-Build" \
          --build-number="${{ github.run_id }}"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    # 构建项目
    - name: Build Project
      run: |
        jfrog rt dotnet build dotnet-sample/dotnet-sample.sln \
          --configuration ${{ matrix.configuration }} \
          --no-restore \
          --build-name="DotNet-Sample-Build" \
          --build-number="${{ github.run_id }}"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    # 运行测试
    - name: Run Tests
      run: dotnet test dotnet-sample/dotnet-sample.sln --configuration ${{ matrix.configuration }} --no-build

    # 发布构建产物
    - name: Publish Artifacts
      run: |
        dotnet publish dotnet-sample/dotnet-sample.sln \
          --configuration ${{ matrix.configuration }} \
          --output ./output
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    # 将构建产物上传到 Artifactory
    - name: Upload Artifacts to Artifactory
      run: |
        jfrog rt upload "dotnet-sample/output/**/*" \
          "dotnet-sample-repo/${{ matrix.configuration }}/" \
          --build-name="DotNet-Sample-Build" \
          --build-number="${{ github.run_id }}"

    # 发布构建信息到 Artifactory
    - name: Publish Build Info to Artifactory
      run: |
        jfrog rt build-publish "DotNet-Sample-Build" "${{ github.run_id }}"
